### ISSUE TITLE
Plugin not updating in Galaxy - stuck at 0.5.13

### ISSUE THREAD

**Issue by grnassar** [tylerbrawl/Galaxy-Plugin-Rockstar#158]
I see that the plugin has gone through 0.5.14 and 0.5.15 releases from the changelogs, but my version in GOG Galaxy is still at 0.5.13.  It would seem I am not the only one, as someone else mentioned having this issue back on 23 Jan, in issue #143 .

My current manifest:
{
    "name": "Rockstar Integration Plugin for Galaxy 2.0",
    "platform": "rockstar",
    "guid": "774732b5-69c4-405c-b6c9-92cd55740cfe",
    "version": "0.5.13",
    "description": "This plugin will allow for (basic) integration with the Rockstar Games Launcher.",
    "author": "Tylerbrawl",
    "email": "tylerbrawl@gmail.com",
    "url": "https://github.com/tylerbrawl/Galaxy-Plugin-Rockstar",
    "update_url": "https://raw.githubusercontent.com/FriendsOfGalaxy/galaxy-integration-rockstar/master/current_version.json",
    "script": "plugin.py"
}

**Comment by grnassar** [comment]
Apologies.  I see you have a PR open in the downstream FriendsOfGalaxy repo, and have had that opened since January and they still haven't merged.  (For others wondering about this, the PR is here: https://github.com/FriendsOfGalaxy/galaxy-integration-rockstar/pull/22)  Clearly not an issue with this repo.  Closing issue.

**Comment by tylerbrawl** [comment]
Yeah, it's a little strange that it hasn't been merged yet. Thanks for pointing this out. I'll actually go ahead and pin this issue for anybody else who wants to know.

**Comment by tylerbrawl** [comment]
I also want to point out that @gabber7 has been linking to a solution which others have found works for them. The details can be found at https://www.gog.com/forum/general_beta_gog_galaxy_2.0/no_pluginconnection_to_rockstar.

For others entering this thread, please try the above solution before creating a new issue.

**Comment by grnassar** [comment]
Doesn't seem to be a great place anywhere to create an issue downstream (for any of the integrations, really, at least ones that are actually read), so I created one in the API repo -- https://github.com/gogcom/galaxy-integrations-python-api/issues/194 Hopefully it'll  help!

**Comment by Slashbunny** [comment]
@tylerbrawl if you do a release for `0.5.15` in this repository, I can update my downloader to pull from this repo instead of FriendsOfGalaxy's repo. 

Per this thread it looks like the Github Actions automation to update downstream plugins was disabled after 60 days of inactivity from the user who set it up: https://github.com/UncleGoogle/galaxy-integration-humblebundle/issues/176 so nothing has been updated since then.

**Comment by tylerbrawl** [comment]
@Slashbunny - Alright, I just submitted a release for `0.5.15` at https://github.com/tylerbrawl/Galaxy-Plugin-Rockstar/releases/tag/v0.5.15. I can't guarantee that it will work out of the box, however. Last I remember, Rockstar made some changes which broke the method used by the plugin to check the user's tracked games. Truth be told, I haven't had the time recently to work on figuring that out. Real life gets in the way of that stuff nowadays.

Anyways, do let me know if there is a specific format in which the .zip file needs to be archived. I just used the same format as all of the previous releases.

**Comment by Slashbunny** [comment]
That works fine, I updated the plugin manifest with the new release so anyone using my downloader should get the new version:

https://github.com/Slashbunny/gog-galaxy-plugin-downloader/commit/cafcd27c916f2b3e5fcbb88f04f077d9564a7a7d

**Comment by simonjonnemeth** [comment]
> @Slashbunny - Alright, I just submitted a release for `0.5.15` at https://github.com/tylerbrawl/Galaxy-Plugin-Rockstar/releases/tag/v0.5.15. I can't guarantee that it will work out of the box, however. Last I remember, Rockstar made some changes which broke the method used by the plugin to check the user's tracked games. Truth be told, I haven't had the time recently to work on figuring that out. Real life gets in the way of that stuff nowadays.
> 
> Anyways, do let me know if there is a specific format in which the .zip file needs to be archived. I just used the same format as all of the previous releases.

Even as of 0.5.15 none of my games show in GOG Galaxy.

**Comment by Krzysztof23** [comment]
sorry to reopen the topic, but to be honest I don't know plugins. The plug-in copy I have installed is also stuck on the mentioned version. What exactly should I do to update it?

**Comment by simonjonnemeth** [comment]
> sorry to reopen the topic, but to be honest I don't know plugins. The plug-in copy I have installed is also stuck on the mentioned version. What exactly should I do to update it?

I wouldn't bother. It still doesn't work.

**Comment by dgg555gta** [comment]
Hello, this plugin is still not working nowadays. It stucks after login and shows a white screen. I guess Rockstar changed the APIs. How could I find documentation about those APIs? If I could had this information I could propose a fix for this plugin @tylerbrawl

**Comment by Nutzzz** [comment]
> How could I find documentation about those APIs?

There's some old documentation for the Social Club stuff (that may or may not work anymore). But there's no documentation for this. You'd have to reverse engineer it. I imagine you check the logs and monitor your network traffic.

You *could* start with just getting back to a (admittedly non-ideal) version by commenting out the call to get_owned_games_online() and see if you can rely on the registry for the installed games and the log files for the owned ones.

**Comment by dgg555gta** [comment]
Thank you @Nutzzz but I already found and checked this old documentation and it's useless, it's too old. 

The main value of this plugin is not managing local games, is connecting to Social Club and see from outside the information that we can only see from inside a Rockstar game.

To me, repairing the APIs connections is a must.
